function createfigure_Paper_DataProcess_1(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of semilogx x data
%  YMATRIX1:  matrix of semilogx y data

%  Auto-generated by MATLAB on 18-Jul-2022 22:37:52

% Create figure
figure1 = figure('InvertHardcopy','off','NumberTitle','off','Name','Figure',...
    'Color',[1 1 1],...
    'Renderer','painters');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to semilogx
semilogx1 = semilogx(X1,YMatrix1,'LineWidth',2);
set(semilogx1(1),'DisplayName','Calculation(m=8)','MarkerSize',10,...
    'Marker','*');
set(semilogx1(2),'DisplayName','Simulation(m=8)');
set(semilogx1(3),'DisplayName','Calculation(m=16)','MarkerSize',10,...
    'Marker','^');
set(semilogx1(4),'DisplayName','Simulation(m=16)');

% Create ylabel
ylabel('HD3 [dB]','LineWidth',2,'FontWeight','bold','FontSize',14,...
    'FontName','arial');

% Create xlabel
xlabel('Frequency [Hz]','LineWidth',2,'FontWeight','bold','FontSize',14,...
    'FontName','arial');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1E4 5E7]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-190 -65]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','arial','FontSize',14,'FontWeight','bold','LineWidth',...
    2,'XMinorTick','on','XScale','log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest','LineWidth',2,'FontSize',14);

